[package]
name = "gnss-qc"
version = "0.0.2"
license = "MPL-2.0"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]
description = "GNSS data Quality Control"
homepage = "https://github.com/rtk-rs"
repository = "https://github.com/rtk-rs/gnss-qc"
keywords = ["geo", "gnss", "gps"]
categories = ["science", "science::geo"]
edition = "2021"

[features]
default = [] # no features by default

# Unlock support of high precision SP3 files.
# When targetting highest precision analysis and solutions, like in PPP,
# SP3 files are mandatory. When deactivated, we simply cannot load
# such files into a context, only RINEX post processing is possible.
sp3 = ["dep:sp3"]

# Unlock graphical analysis (plots rendering), otherwise reports are solely text based
# plot = [
#     "dep:plotly", 
# ]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docrs", "--generate-link-to-definition"]

[dependencies]
log = "0.4"
thiserror = "2"

strum = "0.26"
strum_macros = "0.26"
itertools = "0.13.0"
map_3d = "0.1.5"
serde = { version = "1.0", default-features = false, features = ["derive"] }

hifitime = "4.0"
anise = { version = "0.5.3", features = ["embed_ephem"] }
gnss-rs = { version = "2.3.3", features = ["serde"] }
gnss-qc-traits = { version = "0.1.0", features = ["processing"] }

maud = "0.26"
plotly = "0.9"

rinex = { git = "https://github.com/georust/rinex", branch = "main",  features = ["qc", "processing", "obs", "clock", "nav", "ionex", "serde"]  }

sp3 = { git = "https://github.com/georust/rinex", branch = "main", features = ["qc", "processing", "serde"], optional = true }

[dev-dependencies]
serde_json = "1"
