[package]
name = "gnss-qc"
version = "0.0.1"
license = "MPL-2.0"
authors = ["Guillaume W. Bres <guillaume.bressaix@gmail.com>"]
description = "GNSS data Quality Control"
homepage = "https://github.com/rtk-rs/gnss-qc"
repository = "https://github.com/rtk-rs/gnss-qc"
keywords = ["rinex", "gnss", "gps", "glonass", "galileo"]
categories = ["science", "science::geo"]
edition = "2021"

[features]
default = [] # no features by default

# Unlock support of high precision SP3 files.
# When targetting highest precision analysis and solutions, like in PPP,
# SP3 files are mandatory. When deactivated, we simply cannot load
# such files into a context, only RINEX post processing is possible.
sp3 = ["dep:sp3"]

# Unlock graphical analysis (plots rendering), otherwise reports are solely text based
# plot = [
#     "dep:plotly", 
# ]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docrs", "--generate-link-to-definition"]

[dependencies]
log = "0.4"
thiserror = "2"

strum = "0.26"
strum_macros = "0.26"
itertools = "0.13.0"
serde = { version = "1.0", default-features = false, features = ["derive"] }

map_3d = "0.1.5"

hifitime = "4.0"
anise = { version = "0.5.2", features = ["embed_ephem"] }
gnss-rs = { version = "2.3.1", features = ["serde"] }
gnss-qc-traits = { path = "../traits", version = "=0.0.1", features = ["processing"] }

maud = "0.26"

plotly = "0.9"
# plotly = { path = "../../plotly-rs/plotly" }
# plotly = { git = "https://github.com/gwbres/plotly", branch = "scattergeo"} 

# SP3 lib
sp3 = { path = "../../../rinex/sp3", version = "=1.1.0-alpha-1", features = ["qc", "processing", "serde"], optional = true }

# RINEX lib
rinex = { path = "../../../rinex/rinex", version = "=0.17.0-alpha-1", features = ["full"] }

[dev-dependencies]
serde_json = "1"
