name: Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # midnight, every day

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      name: Install Rust
      with:
        toolchain: stable
        override: true

    - name: Build (Default)
      run: cargo build
    
    - name: Build (SP3)
      run: cargo build --features sp3
    
    - name: Build (all features)
      run: cargo build --all-features
    
    - name: Run tests
      run: cargo test --all-features
