name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    
    - name: Build (Default)
      run: cargo build
    
    - name: Build (SP3)
      run: cargo build --features sp3
    
    - name: Build (all features)
      run: cargo build --all-features
    
    - name: Run tests
      run: cargo test --all-features
  
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ['build']
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Publish
        env:
          TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo login $TOKEN
          cargo publish --allow-dirty
