name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0
    
    - name: Build (Default)
      run: cargo build
    
    - name: Clean
      run: cargo clean
    
    - name: Build (SP3)
      run: cargo build --features sp3
    
    - name: Clean
      run: cargo clean
    
    - name: Build (all features)
      run: cargo build --all-features
    
    - name: Clean
      run: cargo clean
    
    - name: Run tests
      run: cargo test --all-features
