name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build (Default)
      run: cargo build --verbose
    - name: Build (SP3)
      run: cargo build --features sp3
    - name: Build (All)
      run: cargo build --all-features
    - name: Run tests
      run: cargo test --all-features --verbose
